In [1]:
#If you only use the arrange function, it will output a one-dimensional array.
#To make it a two-dimensional array, chain its output with the reshape function.
#here we  will create the 15 integers and then it will convert to two dimensional array with 3 rows and 5 columns.

In [4]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print("Shape of the numpy array is =", a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Shape of the numpy array is = (3, 5)


In [ ]:
#Accessing numpy 2D array

In [5]:
a = np.arange(15).reshape(3,5)
print(a)

print("Element in 1st row and 1st column =",a[0,0])
print("Element in 2nd row and 5th column =",a[1,4])
print("Element in 3rd row and 4th column =",a[2,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Element in 1st row and 1st column = 0
Element in 2nd row and 5th column = 9
Element in 3rd row and 4th column = 13
